// Package vector implements msgvault's semantic and hybrid search over
// the email corpus. Embeddings are generated by an external
// OpenAI-compatible endpoint; vectors are stored in a separate
// ~/.msgvault/vectors.db. See docs/superpowers/specs/2026-04-19-vector-search-design.md.
package vector

import (
	"fmt"
	"net/url"
	"time"
)

// Config is the top-level vector-search configuration, loaded from the
// [vector] TOML table.
type Config struct {
	Enabled    bool             `toml:"enabled"`
	Backend    string           `toml:"backend"` // "sqlite-vec" (MVP); "lance" reserved
	DBPath     string           `toml:"db_path"` // backend-specific
	Embeddings EmbeddingsConfig `toml:"embeddings"`
	Preprocess PreprocessConfig `toml:"preprocess"`
	Search     SearchConfig     `toml:"search"`
	Embed      EmbedConfig      `toml:"embed"`
}

// EmbeddingsConfig configures the external OpenAI-compatible
// embedding endpoint used to convert message text into vectors.
type EmbeddingsConfig struct {
	Endpoint      string        `toml:"endpoint"`
	APIKeyEnv     string        `toml:"api_key_env"`
	Model         string        `toml:"model"`
	Dimension     int           `toml:"dimension"`
	BatchSize     int           `toml:"batch_size"`
	Timeout       time.Duration `toml:"timeout"`
	MaxRetries    int           `toml:"max_retries"`
	MaxInputChars int           `toml:"max_input_chars"`
	ETAWindow     int           `toml:"eta_window"`
}

// PreprocessConfig controls message text preprocessing before embedding.
//
// Fields are pointers so the decoder can distinguish "unset" (nil,
// defaults to true) from an explicit `false` in the TOML file. Call the
// StripQuotesEnabled / StripSignaturesEnabled helpers to resolve the
// effective value.
type PreprocessConfig struct {
	StripQuotes     *bool `toml:"strip_quotes"`
	StripSignatures *bool `toml:"strip_signatures"`
}

// StripQuotesEnabled returns the effective strip_quotes setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripQuotesEnabled() bool {
	if p.StripQuotes == nil {
		return true
	}
	return *p.StripQuotes
}

// StripSignaturesEnabled returns the effective strip_signatures setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripSignaturesEnabled() bool {
	if p.StripSignatures == nil {
		return true
	}
	return *p.StripSignatures
}

// SearchConfig controls hybrid-search ranking and result limits.
//
// MaxPageSizeHybrid is a *int so an omitted field (nil) can be told
// apart from an explicit 0 in the TOML file. ApplyDefaults fills in
// 50 only when nil; explicit `max_page_size_hybrid = 0` is preserved
// and disables the per-request clamp entirely. Use the
// MaxPageSizeHybridClamp helper to read the effective value at the
// API/MCP boundary.
type SearchConfig struct {
	RRFK              int     `toml:"rrf_k"`
	KPerSignal        int     `toml:"k_per_signal"`
	SubjectBoost      float64 `toml:"subject_boost"`
	MaxPageSizeHybrid *int    `toml:"max_page_size_hybrid"`
}

// MaxPageSizeHybridClamp returns the effective per-request limit
// clamp: zero means "no clamp", a positive value means "clamp to N".
// Helper exists because callers want a flat int and need to handle
// the nil-pointer "unset" case identically to an explicit 0.
func (s SearchConfig) MaxPageSizeHybridClamp() int {
	if s.MaxPageSizeHybrid == nil {
		return 0
	}
	return *s.MaxPageSizeHybrid
}

// EmbedConfig groups embed-side concerns that aren't part of the
// embedding endpoint itself (e.g. scheduling).
type EmbedConfig struct {
	Schedule EmbedScheduleConfig `toml:"schedule"`
}

// EmbedScheduleConfig controls when the embed worker runs on its own
// (outside of explicit `msgvault build-embeddings` invocations).
type EmbedScheduleConfig struct {
	Cron         string `toml:"cron"`           // empty disables scheduled embedding
	RunAfterSync bool   `toml:"run_after_sync"` // trigger after each successful sync
}

// Fingerprint returns the "<model>:<dimension>" identifier used by the
// index-generation check (§6.7 of the spec).
func (e EmbeddingsConfig) Fingerprint() string {
	return fmt.Sprintf("%s:%d", e.Model, e.Dimension)
}

// Validate returns a descriptive error if the config is unusable.
// Only called when Enabled is true; disabled configs are not checked.
func (c *Config) Validate() error {
	if c.Backend != "sqlite-vec" {
		return fmt.Errorf("vector.backend: unknown backend %q (only \"sqlite-vec\" is supported in MVP)", c.Backend)
	}
	if c.Embeddings.Endpoint == "" {
		return fmt.Errorf("vector.embeddings.endpoint: required")
	}
	u, err := url.Parse(c.Embeddings.Endpoint)
	if err != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") {
		return fmt.Errorf("vector.embeddings.endpoint: must be an http or https URL with a host (got %q)", c.Embeddings.Endpoint)
	}
	if c.Embeddings.Model == "" {
		return fmt.Errorf("vector.embeddings.model: required (the index generation fingerprint is %q, which is ambiguous without a model name)", c.Embeddings.Fingerprint())
	}
	if c.Embeddings.Dimension <= 0 {
		return fmt.Errorf("vector.embeddings.dimension: must be positive, got %d", c.Embeddings.Dimension)
	}
	if c.Embeddings.BatchSize <= 0 {
		return fmt.Errorf("vector.embeddings.batch_size: must be positive, got %d", c.Embeddings.BatchSize)
	}
	return nil
}

// ApplyDefaults fills in sensible defaults for any zero-valued fields.
// Called after TOML decode, before Validate.
func (c *Config) ApplyDefaults() {
	if c.Backend == "" {
		c.Backend = "sqlite-vec"
	}
	if c.Embeddings.BatchSize == 0 {
		c.Embeddings.BatchSize = 32
	}
	if c.Embeddings.Timeout == 0 {
		c.Embeddings.Timeout = 30 * time.Second
	}
	if c.Embeddings.MaxRetries == 0 {
		c.Embeddings.MaxRetries = 3
	}
	if c.Embeddings.MaxInputChars == 0 {
		c.Embeddings.MaxInputChars = 32768
	}
	if c.Embeddings.ETAWindow <= 0 {
		c.Embeddings.ETAWindow = 10
	}
	if c.Search.RRFK == 0 {
		c.Search.RRFK = 60
	}
	if c.Search.KPerSignal == 0 {
		c.Search.KPerSignal = 100
	}
	if c.Search.SubjectBoost == 0 {
		c.Search.SubjectBoost = 2.0
	}
	if c.Search.MaxPageSizeHybrid == nil {
		v := 50
		c.Search.MaxPageSizeHybrid = &v
	}
	// Preprocess booleans are *bool so unset (nil) means "default true"
	// without overwriting an explicit false from the config file. The
	// StripQuotesEnabled / StripSignaturesEnabled helpers resolve the
	// effective value.
}

// APIKey resolves the API key from the env var named in APIKeyEnv.
// Returns "" if APIKeyEnv is empty or the variable is unset.
func (e EmbeddingsConfig) APIKey() string {
	if e.APIKeyEnv == "" {
		return ""
	}
	return lookupEnv(e.APIKeyEnv)
}
